version: '3.8'

services:
  db:
    image: postgres
    container_name: assessment4_db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: craigslist_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  api:
    build: .
    container_name: assessment4_api
    command: >
      sh -c "python manage.py migrate &&
             python manage.py dummy_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
